;;; -*- lexical-binding: t -*-

(eon-max-gc-limit)

(setq load-prefer-newer t)
(add-to-list 'load-path (expand-file-name "eon-lisp" user-emacs-directory))

(defgroup eon nil
  "自定义配置组"
  :prefix "eon-")

(require 'eon-env)
(require 'eon-secrets nil t)
(require 'eon-lib)
(require 'eon-input-method)
(require 'eon-font)
(require 'eon-treesit)
(require 'eon-generic)
(require 'eon-window-op)
(require 'eon-dired)
(require 'eon-yasnippet)
(require 'eon-vcs)
(require 'eon-auto-format)
(require 'eon-editor)
(require 'eon-autosave)
(require 'eon-work)
(require 'eon-dot)
(require 'eon-org)
(require 'eon-lsp)
(require 'eon-program)
(require 'eon-protobuf)
(require 'eon-lisp)
(require 'eon-c-c++)
(require 'eon-cmake)
(require 'eon-selection-op)
(require 'eon-go)
(require 'eon-js-ts-css-html)
(require 'eon-bash)
(require 'eon-project)
(require 'eon-yaml)
(require 'eon-nix)
(require 'eon-docker)
(require 'eon-nginx)
(require 'eon-python)
(require 'eon-buffer-op)
(require 'eon-jenkinsfile)
;; (require 'eon-java)
(require 'eon-make)
(require 'eon-lua)
(require 'eon-clojure)
(require 'eon-chinese)
(require 'eon-modalka)
(require 'eon-avy)
(require 'eon-compilation)
(require 'eon-pdf)
(require 'eon-info-help)
(require 'eon-diff)
(put 'narrow-to-region 'disabled nil)
